version: '3'

networks:
  default:
    driver: bridge

services:
  db:
      image: mysql:5.7
      networks:
        - default
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: yii
        MYSQL_USER: admin
        MYSQL_PASSWORD: root
      volumes:
        - "./db:/var/lib/mysql"
  app:
      build: .
      restart: always
      ports:
        - "28480:80"
        - "28433:433"
      networks:
        - default
      depends_on:
        - db
      volumes:
       - "/var/www/merlinmanager-web:/app"

