version: '3.4'

networks:
  default:

volumes:
  merlin-backend-mysql-data:
    external: true

services:
  nginx:
    build:
      context: ./local
      dockerfile: Dockerfile_nginx
    container_name: merlin_backend_nginx
    restart: always
    networks:
      - default
    ports:
      - 2860:80
    volumes:
      - &data-app ../:/app
      - ./local/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./local/config/nginx/site.conf:/etc/nginx/site.conf
    depends_on:
      - fpm

  fpm:
    build:
      context: ./local
      dockerfile: Dockerfile_fpm
    volumes:
      - *data-app
      - ./local/config/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./local/config/fpm/php.ini:/usr/local/etc/php/php.ini
    working_dir: /app
    container_name: merlin_backend_fpm
    depends_on:
      - database

  database:
    image: mysql:5.7
    container_name: merlin_backend_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: yii
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - merlin-backend-mysql-data:/var/lib/mysql
    ports:
      - 5440:5432
