- hosts: localhost
  tasks:
    - name: set env vars
      raw: export VERSION={{lookup('env','VERSION')}}

    - name: docker build
      raw: docker-compose -f ../docker/docker-compose.dev.yml build
      #register: docker_compose_build

    - name: docker login
      raw: docker login -u test -p {{lookup('env','registrypassword')}} registry.handh.ru

    - name: docker push
      raw: docker-compose -f ../docker/docker-compose.dev.yml push

  #- debug:  var=docker_compose_build.stdout_lines

- hosts: dev
  tasks:
    - name: copy file
      copy:
        src: ../docker/docker-compose.dev.yml
        dest: /var/www/merlin-manager/docker-compose.dev.yml
    - name: docker-compose pull and down and up
      shell: |
        export VERSION={{lookup('env','VERSION')}}
        export COMPOSE_INTERACTIVE_NO_CLI=1
        export PROJECT_NAME={{lookup('env','PROJECT_NAME')}}
        docker login -u test -p {{lookup('env','registrypassword')}} registry.handh.ru
        mkdir -p common dev local prod release
        docker-compose -f docker-compose.dev.yml pull
        docker-compose -p merlin-manager-handh -f docker-compose.dev.yml down -v
        docker-compose -p merlin-manager-handh -f docker-compose.dev.yml up -d
        sleep 10
#        docker exec -t merlin_backend_fpm php yii migration --no-interaction
      args:
        chdir: /var/www/merlin-manager
  #- debug:  var=ls.stdout_lines